name: Changelog
on: workflow_call

jobs:
  changelog:
    name: create changelog and release result
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get current commit info
        run: |
          echo ## Last commit
          git log --name-status HEAD^..HEAD >> changelog.md
          echo "++++++++++++++++++++++++++++++++++" >> changelog.md
      # Формирование коммитов
      - name: Get current and previous tag
        run: |
          echo PREV_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1  --max-count=1)) >> $GITHUB_ENV
          echo CUR_TAG=$(git describe --abbrev=0 --tags) >> $GITHUB_ENV
