name: linting, testing, building
on:
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build production project
        run: npm run build
        if: always()
      - name: unit testing
        run: npm run test-ci
      - name: install chromium for e2e
        run: npx playwright install --with-deps chromium
      - name: e2e testing
        run: npm run e2e-ci
