name: Create Release and deploy
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo tag
        run: echo ${{ github.ref }}
      - name: Release Changelog Builde
        id: build_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        uses: mikepenz/release-changelog-builder-action@v4.0.0-rc03
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            changelog: ${{steps.build_changelog.outputs.changelog}}
            owner: ${{steps.build_changelog.outputs.owner}}
            repo: ${{steps.build_changelog.outputs.repo}}
            fromTag: ${{steps.build_changelog.outputs.fromTag}}
            toTag: ${{steps.build_changelog.outputs.toTag}}
            failed: ${{steps.build_changelog.outputs.failed}}
            pull_requests: ${{steps.build_changelog.outputs.pull_requests}}
            categorized_prs: ${{steps.build_changelog.outputs.categorized_prs}}
            open_prs: ${{steps.build_changelog.outputs.open_prs}}
            uncategorized_prs: ${{steps.build_changelog.outputs.uncategorized_prs}}
            changed_files: ${{steps.build_changelog.outputs.changed_files}}
            additions: ${{steps.build_changelog.outputs.additions}}
            deletions: ${{steps.build_changelog.outputs.deletions}}
            changes: ${{steps.build_changelog.outputs.changes}}
            commits: ${{steps.build_changelog.outputs.commits}}
            categorized: ${{steps.build_changelog.outputs.categorized}}
            cache: ${{steps.build_changelog.outputs.cache}}
          draft: false
          prerelease: false

  changelog:
    name: Create release info
    needs: release
    uses: ./.github/workflows/changelog.yml
    secrets: inherit
    permissions:
      id-token: write
      issues: write
  
  # Deployment job
  deploy:
    name: Deploy
    needs: release
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
