name: Create Release and deploy
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo tag
        run: echo ${{ github.ref }}
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: true

  # Deployment job
  deploy:
    name: Deploy
    needs: release
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
