name: Create Release and deploy
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

#Разрешения
permissions:
  contents: write
  pages: write
  issues: 'write'
  id-token: write

# Комплекс операций
jobs:
  ######################
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: build production project
        run: npm run build
        if: always()
      - name: unit testing
        run: npm run test-ci
      - name: install chromium for e2e
        run: npx playwright install --with-deps chromium
      - name: e2e testing
        run: npm run e2e-ci

  ######################      
  release:
    name: Create release
    needs: test
    runs-on: ubuntu-latest
    steps:
      ######################
      - name: Checkout code
        uses: actions/checkout@v2

      ######################
      - name: Echo tag
        run: echo ${{ github.ref }}

      ######################
      - name: Create information for changelog
        id: build_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: mikepenz/release-changelog-builder-action@v4.0.0-rc03

        ######################
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            fromTag: ${{steps.build_changelog.outputs.fromTag}}
            toTag: ${{steps.build_changelog.outputs.toTag}}
            commits: ${{steps.build_changelog.outputs.commits}}
            cache: ${{steps.build_changelog.outputs.cache}}
          draft: false
          prerelease: false

        ######################
      - name: GetDate
        run: export DATE=`date`
      - name: Create Release Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue create --title "RELEASE ${{ steps.build_changelog.outputs.toTag }}" --body "Автор - ${{steps.build_changelog.outputs.owner}} Дата $DATE"

  # Deployment job
  deploy:
    name: Deploy
    needs: release
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
